### ISSUE TITLE
Why the a b and c lattice constant is different of cubic FAPbI3 ?

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [WMD-group/hybrid-perovskites#2]
Hi, I noticed that in 2015_fapbi_PBEsol, the relaxed cubic FAPbI3 POSCAR is 
```bash
FAPI PBEsol optimised (pseudo-cubic Z=1)
 1.0
        6.4074602127         0.0000000000         0.0000000000
        0.0000008343         6.2656202316         0.0000000000
        0.0000000000         0.0000000000         6.3375701904
    C    N    H   Pb    I
    1    2    5    1    3
Direct
     0.500001013         0.520579994         0.500000000
     0.681743026         0.425729990         0.500000000
     0.318255007         0.425729990         0.500000000
     0.500000000         0.695747972         0.500000000
     0.811782002         0.520475984         0.500000000
     0.701974988         0.263390005         0.500000000
     0.298025012         0.263390005         0.500000000
     0.188217998         0.520475984         0.500000000
     0.000000000         0.965927005         0.000000000
     0.500000000         0.984417021         0.000000000
     0.000000000         0.462947994         0.000000000
     0.000000000         0.919703007         0.500000000
```
and lattice constant a b and c are three different values? I want to ask why? Should it be the three equal values for cubic structure?

**Comment by aronwalsh** [comment]
Good question @PolyuWeldingSpock.

For crystals with a molecular component, here formamidinium, there is often orientational disorder. The crystal appears cubic if you average over space and/or time. This is just a simple static representation in a small unit cell, which is labelled "pseudo-cubic".

**Comment by aronwalsh** [comment]
This paper may help you as it discusses various averaging effects: [https://pubs.acs.org/doi/full/10.1021/acs.jpcc.3c03377](https://pubs.acs.org/doi/full/10.1021/acs.jpcc.3c03377)

**Comment by PolyuWeldingSpock** [comment]
@aronwalsh Thanks for your patient reply. The jpcc paper give us great insight of perovskite. However,one more question I want to ask. How to compare the pseudo-cubic lattice parameter with experimental lattice parameters to make sure the computational results are accurate? In other words, how to convert pseudo-cubic lattice constant to real-cubic lattice constant? Is the AIMD the only method?

**Comment by aronwalsh** [comment]
One way to define a pseudocubic lattice constant is from the cubed root of the cell volume. 

As these materials have large thermal expansion coefficients and feature strong anharmonic effects, static DFT calculations have limitations.

Good luck with your study.
